global_frame: map
rolling_window: true
track_unknown_space: false

plugins:
  - {name: static_map_layer,  type: "costmap_2d::StaticLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
#  - {name: obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
