linear_scale: #linear_drive_scale_map
  x: 1.0  #1.0
  y: 1.0  #1.0
  z: 1.0  #1.0
max_positive_linear_velocity:
  x: 1.0  #1.0
  y: 1.0  #1.0
  z: 1.0  #1.0
max_negative_linear_velocity:
  x: -1.0  #-1.0
  y: -1.0  #-1.0
  z: -1.0  #-1.0
angular_scale: #angular_drive_scale
  x: 2.2  #2.2
  y: 2.2  #2.2
  z: 2.2  #2.2
max_positive_angular_velocity:
  x: 2.2  #2.2
  y: 2.2  #2.2
  z: 2.2  #2.2
max_negative_angular_velocity:
  x: -2.2  #-2.2
  y: -2.2  #-2.2
  z: -2.2  #-2.2
