octomap_frame: map
octomap_resolution: 0.02 #0.01 #0.025
max_range: 1.5 #5.0
sensors:
#- sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#  image_topic: /bvr_SIM/l515/aligned_depth_to_color/image_raw
#  queue_size: 1 #5
#  near_clipping_plane_distance: 0.25
#  far_clipping_plane_distance: 1.5 #2.5
#  skip_vertical_pixels: 4 #1
#  skip_horizontal_pixels: 4 #1
#  shadow_threshold: 0.2
#  padding_scale: 4.0
#  padding_offset: 0.03
#  max_update_rate: 5.0 #5.0
#  filtered_cloud_topic: moveit_output_cloud
- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /bvr_SIM/l515/depth/color/points
  max_range: 1.5 #2.5
  point_subsample: 10 #1
  padding_offset: 0.1
  padding_scale: 1.0 #1.0
  max_update_rate: 2.0 #5.0
  filtered_cloud_topic: moveit_output_cloud
