spin_rate: 100  #50 # Hertz
jacobian_frame_name: bvr_SIM/main_arm_SIM/base_link  # MoveIt! planning frame. Often the last link in your tf tree
force_torque_frame_name: bvr_SIM/main_arm_SIM/tool0 # The frame of incoming force/torque data
force_torque_topic: /bvr_SIM/main_arm_SIM/wrench # The topic of incoming force/torque data
force_torque_reference_topic: /bvr_SIM/main_arm_SIM/wrench_reference # The topic of reference force/torque for control
move_group_name: main_arm_SIM # The MoveGroup name of your robot
max_allowable_cmd_magnitude: 0.75  #0.5 # The largest joint speed correction that can be published [rad/s]
outgoing_joint_vel_topic: /bvr_SIM/main_arm_SIMcompliance_controller/compliance_velocity_adjustment # Joint delta-velocities
outgoing_singularity_topic: /bvr_SIM/main_armcompliance_controller/singularity # Joint state when in singularity (published only when singular)
outgoing_jointlimit_topic: /bvr_SIM/main_armcompliance_controller/jointlimit # Joint state when in joint limit state (published only when in joint limit)
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.
condition_number_limit: 100  #50 # The Jacobian condition number above which to pause compliance
condition_number_hysteresis: 95 # The Jacobian condition number below which to restore compliance (has to be lower than condition_number_limit)
compliance_library:
# Key equation: compliance_velocity[i] = wrench[i]/stiffness[i]
  stiffness: [75, 75, 75, 5, 5, 5] # First three element are Newtons/(m/s), last 3 are N*m/(rad/s). Should be positive.
  damping: [10000, 10000, 10000, 10000, 10000, 10000] # First three element are Newtons/m, last 3 are N*m/rad. Should be positive.
  low_pass_filter_param: 20 # Larger > more smoothing on compliance calcs, but more lag
  deadband: [5.0, 5.0, 5.0, 0.25, 0.25, 0.25] # No reaction until force exceeds X [N, N, N, Nm, Nm, Nm]
  end_condition_wrench: [80, 80, 80, 60, 60, 60] # Safety feature. Halt if force exceeds [N, N, N, Nm, Nm, Nm]
  highest_allowable_force: 88 # Safety feature. Halt if force magnitude exceeds this across all dimensions [N]
  highest_allowable_torque: 50 # Safety feature. Halt if torque magnitude exceeds this across all dimensions [Nm]
  # Defines which directions (true's) the compliance starts in
  # Order is [translation-x, translation-y, translation-z, rotation-x, rotation-y, rotation-z]
  default_compliant_dimensions: [1, 1, 1, 1, 1, 1] 
