linear_scale:
  x: 1
  y: 1
  z: 1
max_positive_linear_velocity:
  x: 1
  y: 1
  z: 1
max_negative_linear_velocity:
  x: -1
  y: -1
  z: -1
angular_scale:
  x: 1
  y: 1
  z: 1
max_positive_angular_velocity:
  x: 1
  y: 1
  z: 1
max_negative_angular_velocity:
  x: -1
  y: -1
  z: -1
